// THIS FILE IS GENERATED. EDITING IS FUTILE.
//
// Generated by "thema lineage gen" from lineage defined in dashboard_kind.cue

package main

// Dashboard defines model for dashboard.
type Dashboard struct {
	Header *string `json:"header,omitempty"`
	Title  string  `json:"title"`
}
